const actionsTypes = {
  CART_REQUEST: 'CART_REQUEST',
  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',
  SELECT_SIZE_PRODUCT: 'SELECT_SIZE_PRODUCT',
  INCREMENT_QUANTITY_PRODUCT: 'INCREMENT_QUANTITY_PRODUCT',
  DECREMENT_QUANTITY_PRODUCT: 'DECREMENT_QUANTITY_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  CLEAN_CART: 'CLEAN_CART',
}

export default actionsTypes;