const actionsTypes = {
  REQUEST_PRODUCTS: 'REQUEST_PRODUCTS',
  SUCCESS_PRODUCTS: 'SUCCESS_PRODUCTS',
  FAILURE_PRODUCTS: 'FAILURE_PRODUCTS',
  
  ADD_PRODUCTS: 'ADD_PRODUCTS',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',

  REQUEST_PRODUCT: 'REQUEST_PRODUCT',
  SUCCESS_PRODUCT: 'SUCCESS_PRODUCT',
  FAILURE_PRODUCT: 'FAILURE_PRODUCT',

  SEARCH_PRODUCTS: 'SEARCH_PRODUCTS',
  SUCCESS_SEARCH_PRODUCTS: 'SUCCESS_SEARCH_PRODUCTS',
  FAILURE_SEARCH_PRODUCTS: 'FAILURE_SEARCH_PRODUCTS',
}

export default actionsTypes;